/* Wonder Academy - pronounce.js
   Rules applied to text right before it is spoken, so the narrator says
   Islamic names and terms properly. Add your own lines at the bottom.
   Each rule is [pattern, replacement]. Replacement can be a function. */
window.PRONOUNCE = [
  /* Honorifics and abbreviations */
  [/ﷺ/g, ', sallallahu alayhi wa sallam,'],
  [/\(AS\)/g, ', alayhis salaam,'],
  [/\(RA\)/g, function (m, offset, str) {
    var before = str.slice(Math.max(0, offset - 40), offset);
    return /(Khadijah|Maryam|Aisha|Fatimah|Hajar|Hawwa|Asiya|Zaynab|Hafsa)[^A-Za-z]*$/i.test(before)
      ? ', radiyallahu anha,' : ', radiyallahu anhu,';
  }],
  [/\bRA\b(?= after| means)/g, 'R A'],
  [/\bAS\b(?= after| means)/g, 'A S'],

  /* Names of Allah and core terms */
  [/\bAllah\b/g, 'Al-laah'],
  [/\bQuran\b/g, 'Qur-aan'],
  [/\bQuranic\b/g, 'Qur-aanic'],
  [/\bIslam\b/g, 'Iss-laam'],
  [/\bMuslims?\b/g, function (m) { return m.length > 6 ? 'Muss-lims' : 'Muss-lim'; }],
  [/\bMakkah\b/g, 'Mak-kah'],
  [/\bMakkan\b/g, 'Mak-kan'],
  [/\bMadinah\b/g, 'Ma-dee-nah'],
  [/\bMadinan\b/g, 'Ma-dee-nan'],
  [/\bKaaba\b/g, 'Kaa-bah'],
  [/\bHajj\b/g, 'Hudge'],
  [/\bUmrah\b/g, 'Um-rah'],
  [/\bJannah\b/g, 'Jun-nah'],
  [/\bZamzam\b/g, 'Zum-zum'],
  [/\bAdhan\b/g, 'A-thaan'],
  [/\bMuadhin\b/g, 'Moo-uz-zin'],
  [/\bMasjid\b/g, 'Mus-jid'],
  [/\bNabawi\b/g, 'Na-ba-wee'],
  [/\bSurah\b/g, 'Soo-rah'],
  [/\bAyah\b/g, 'Aa-yah'],
  [/\bHafiz\b/g, 'Haa-fiz'],
  [/\bTafsir\b/g, 'Taf-seer'],
  [/\bHadith\b/g, 'Ha-deeth'],
  [/\bSabr\b/g, 'Sub-r'],
  [/\bTawbah\b/g, 'Tow-bah'],
  [/\bTawheed\b/g, 'Tow-heed'],
  [/\bTawakkul\b/g, 'Ta-wuk-kul'],
  [/\bTawaf\b/g, 'Ta-waaf'],
  [/\bSa'i\b/g, 'Sa-ee'],
  [/\bQiblah\b/g, 'Kib-lah'],
  [/\bKiswah\b/g, 'Kiss-wah'],
  [/\bHijrah\b/g, 'Hij-rah'],
  [/\bHijri\b/g, 'Hij-ree'],
  [/\bIqra\b/g, 'Ik-rah'],
  [/\bRiba\b/g, 'Ri-baa'],
  [/\bFitna\b/g, 'Fit-nah'],
  [/\bRidda\b/g, 'Rid-dah'],
  [/\bMushaf\b/g, 'Mus-haf'],
  [/\bJinn\b/g, 'Jin'],
  [/\bAnsar\b/g, 'An-saar'],
  [/\bAnsari\b/g, 'An-saa-ree'],
  [/\bMuhajir(un)?\b/g, 'Mu-haa-jir'],
  [/\bMu'akhah\b/g, 'Mu-aa-khah'],
  [/\bEid al-Adha\b/g, 'Eed al-Ud-ha'],
  [/\bEid al-Fitr\b/g, 'Eed al-Fit-r'],
  [/\bRamadan\b/g, 'Ra-ma-daan'],
  [/\bSalaam\b/g, 'Sa-laam'],

  /* Prophets and people */
  [/\bMuhammad\b/g, 'Moo-hum-mad'],
  [/\bIbrahim\b/g, 'Ib-raa-heem'],
  [/\bIsmail\b/g, 'Iss-maa-eel'],
  [/\bIshaq\b/g, 'Iss-haaq'],
  [/\bYaqub\b/g, 'Ya-qoob'],
  [/\bYusuf\b/g, 'You-suf'],
  [/\bMusa\b/g, 'Moo-sa'],
  [/\bHarun\b/g, 'Haa-roon'],
  [/\bIsa\b/g, 'Ee-sa'],
  [/\bNuh\b/g, 'Nooh'],
  [/\bHud\b/g, 'Hood'],
  [/\bSalih\b/g, 'Saa-lih'],
  [/\bAyyub\b/g, 'Ay-yoob'],
  [/\bDawud\b/g, 'Daa-wood'],
  [/\bSulaiman\b/g, 'Su-lay-maan'],
  [/\bYunus\b/g, 'You-nus'],
  [/\bIdris\b/g, 'Id-rees'],
  [/\bAdam\b/g, 'Aa-dam'],
  [/\bHawwa\b/g, 'How-waa'],
  [/\bHajar\b/g, 'Haa-jar'],
  [/\bMaryam\b/g, 'Mar-yam'],
  [/\bKhadijah\b/g, 'Kha-dee-jah'],
  [/\bAminah\b/g, 'Aa-mi-nah'],
  [/\bFatimah\b/g, 'Faa-ti-mah'],
  [/\bAisha\b/g, 'Aa-i-shah'],
  [/\bAbu Bakr\b/g, 'Ah-boo Bak-r'],
  [/\bAbu Talib\b/g, 'Ah-boo Taa-lib'],
  [/\bAbdul Muttalib\b/g, 'Ab-dul Mut-ta-lib'],
  [/\bAbdullah\b/g, 'Ab-dul-laah'],
  [/\bUmar\b/g, 'Oo-mar'],
  [/\bUthman\b/g, 'Uth-maan'],
  [/\bAli\b/g, 'Ah-lee'],
  [/\bBilal\b/g, 'Bi-laal'],
  [/\bHamza\b/g, 'Hum-zah'],
  [/\bWaraqah\b/g, 'Wa-ra-qah'],
  [/\bJibreel\b/g, 'Jib-reel'],
  [/\bMikaeel\b/g, 'Mee-kaa-eel'],
  [/\bIblees\b/g, 'Ib-lees'],
  [/\bFiraun\b/g, 'Fir-own'],
  [/\bJalut\b/g, 'Jaa-loot'],
  [/\bTalut\b/g, 'Taa-loot'],
  [/\bQuraysh\b/g, 'Qu-raysh'],
  [/\bThamud\b/g, 'Tha-mood'],
  [/\bMadyan\b/g, 'Mad-yan'],
  [/\bAbraha\b/g, 'Ab-ra-hah'],
  [/\bHalimah\b/g, 'Ha-lee-mah'],
  [/\bAl-Amin\b/g, 'Al-A-meen'],
  [/\bAs-Siddiq\b/g, 'As-Sid-deeq'],
  [/\bAl-Farooq\b/g, 'Al-Faa-rooq'],
  [/\bDhun-Nurayn\b/g, 'Dhun-Noo-rayn'],
  [/\bDhun-Nun\b/g, 'Dhun-Noon'],
  [/\bKhalilullah\b/g, 'Kha-leel-ul-laah'],
  [/\bKalimullah\b/g, 'Ka-leem-ul-laah'],
  [/\bUlul Azm\b/g, 'Oo-lul Azm'],
  [/\bal-Khwarizmi\b/g, 'al-Khwaa-riz-mee'],
  [/\bIbn al-Haytham\b/g, 'Ib-n al-Hay-tham'],
  [/\bHira\b/g, 'Hi-raa'],
  [/\bThawr\b/g, 'Thowr'],
  [/\bUhud\b/g, 'Oo-hud'],
  [/\bBadr\b/g, 'Bud-r'],
  [/\bKhaybar\b/g, 'Khay-bar'],
  [/\bHudaybiyyah\b/g, 'Hu-day-bee-yah'],
  [/\bArafat\b/g, 'A-ra-faat'],
  [/\bSafa\b/g, 'Sa-faa'],
  [/\bMarwa\b/g, 'Mar-wah'],
  [/\bYathrib\b/g, 'Yath-rib'],
  [/\bKufa\b/g, 'Koo-fah'],
  [/\bSaba\b/g, 'Sa-baa'],
  [/\bNineveh\b/g, 'Nin-e-vah'],
  [/\bAl-Fil\b/g, 'Al-Feel'],
  [/\bAl-Alaq\b/g, 'Al-A-laq'],
  [/\bAl-Fatiha\b/g, 'Al-Faa-ti-hah'],
  [/\bAl-Baqarah\b/g, 'Al-Ba-qa-rah'],
  [/\bAl-A'raf\b/g, 'Al-Aa-raaf'],
  [/\bTawrat\b/g, 'Tow-raat'],
  [/\bInjeel\b/g, 'In-jeel'],
  [/\bZabur\b/g, 'Za-boor'],
  [/\bNahj al-Balagha\b/g, 'Nahj al-Ba-laa-ghah'],
  [/\bAhl as-Suffah\b/g, 'Ah-l as-Suf-fah'],

  /* General fixes */
  [/\bCE\b/g, 'C E'],
  [/\bAH\b/g, 'A H'],
  [/\bT-rex\b/g, 'T rex'],
  [/\bkm\b/g, 'kilometres']
];
